 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EnrollmentApp;

import static EnrollmentApp.EnrollmentSystem.datejTextField;
import static EnrollmentApp.EnrollmentSystem.namejTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Godswill
 */
public class EnquirySystem extends javax.swing.JFrame {

    private JFrame frame;
 private static final String url ="jdbc:mysql://localhost:3306";
    private static final String userName = "root";
    private static final String password2="plexus7989";
    
    String[] values;
    
    static Connection connect = null;
    
    public static void EnquirySystem(){
    
     try{
    
    connect = DriverManager.getConnection(url, userName, password2);
    
            System.out.println("Connection Successful");
            
}
       catch(SQLException e){
    System.err.print(e);
}
    
}
    
    private static void insertData(String[] arrayOfDetails){
        EnquirySystem();
        try{
       PreparedStatement  prepared = connect.prepareStatement("INSERT INTO aptechikorodu.enquiry_system_table(dateOfEnrollment, enrollmentNo,firstName,lastName,\n" +
"            address,contactNo,eMail,dateOfBirth,parent_GuardianName,contactNo1,education1,career1,aboutUs1,future_Plan,placement_Assistance) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
      
       
       int count = arrayOfDetails.length;
       
       int noo = 1;
       for(int i=0; i < (count); i++)
       {
           
           prepared.setObject(noo, arrayOfDetails[i]);
           noo++;
       }
        
        prepared.executeUpdate();
        
        String string = "The Details Has Been Inserted Successfully into The Database!";
        JOptionPane.showMessageDialog(null, string);        
        }
        catch(SQLException e){
            System.err.println(e);
        }
        
    }
    private JRadioButton yes;
    private JRadioButton no;
    /**
     * Creates new form EnrollmentForm
     */
    public EnquirySystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateOfEnrollmentjTextField = new javax.swing.JTextField();
        enrollmentNojTextField = new javax.swing.JTextField();
        firstNamejTextField = new javax.swing.JTextField();
        lastNamejTextField = new javax.swing.JTextField();
        addressjTextField = new javax.swing.JTextField();
        contactNojTextField = new javax.swing.JTextField();
        eMailjTextField = new javax.swing.JTextField();
        dateOfBirthjTextField = new javax.swing.JTextField();
        parent_GuardianNamejTextField1 = new javax.swing.JTextField();
        contactNojTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        highSchooljCheckBox = new javax.swing.JCheckBox();
        undergraduatejCheckBox = new javax.swing.JCheckBox();
        graduatejCheckBox = new javax.swing.JCheckBox();
        vocationalSchooljCheckBox = new javax.swing.JCheckBox();
        othersjCheckBox = new javax.swing.JCheckBox();
        othersjTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        seminarjCheckBox = new javax.swing.JCheckBox();
        magazinejCheckBox = new javax.swing.JCheckBox();
        internetjCheckBox = new javax.swing.JCheckBox();
        friends_RelativesjCheckBox = new javax.swing.JCheckBox();
        othersjCheckBox2 = new javax.swing.JCheckBox();
        othersjTextField3 = new javax.swing.JTextField();
        newspaperjCheckBox = new javax.swing.JCheckBox();
        billboardjCheckBox = new javax.swing.JCheckBox();
        cinemajCheckBox = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        marketingjCheckBox = new javax.swing.JCheckBox();
        websiteDesigningjCheckBox = new javax.swing.JCheckBox();
        systemEngineerjCheckBox = new javax.swing.JCheckBox();
        softwareEngineeringjCheckBox = new javax.swing.JCheckBox();
        hadrware_NetworkingjCheckBox = new javax.swing.JCheckBox();
        educationjCheckBox = new javax.swing.JCheckBox();
        undecidedjCheckBox = new javax.swing.JCheckBox();
        otherjCheckBox = new javax.swing.JCheckBox();
        othersjTextField2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        startYourOwnBusinessjCheckBox = new javax.swing.JCheckBox();
        workAsAnITProfessionaljCheckBox = new javax.swing.JCheckBox();
        goAbroadjCheckBox = new javax.swing.JCheckBox();
        othersjCheckBox4 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        nojRadioButton = new javax.swing.JRadioButton();
        yesjRadioButton = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        updatejButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        resetjButton = new javax.swing.JButton();
        prescriptionjButton = new javax.swing.JButton();
        loginjButton = new javax.swing.JButton();
        exitjButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EnrollmentForm");
        setBackground(new java.awt.Color(153, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setName("EnrollmentForm"); // NOI18N

        jPanel1.setAutoscrolls(true);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Godswill\\Downloads\\aptech logo.png")); // NOI18N
        jButton1.setAutoscrolls(true);

        jPanel2.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("ENQUIRY FORM SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setAutoscrolls(true);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Date of Enrollment:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Enrollment No:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("First Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Last Name:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Address:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Contact No:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("E-Mail:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Parent/Guardian's Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Guardian's Contact No:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Date of Birth:");

        dateOfEnrollmentjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateOfEnrollmentjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfEnrollmentjTextFieldActionPerformed(evt);
            }
        });

        enrollmentNojTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enrollmentNojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentNojTextFieldActionPerformed(evt);
            }
        });

        firstNamejTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lastNamejTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addressjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        contactNojTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        eMailjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dateOfBirthjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        parent_GuardianNamejTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        contactNojTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(parent_GuardianNamejTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(dateOfBirthjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eMailjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactNojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNamejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNamejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enrollmentNojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfEnrollmentjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactNojTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfEnrollmentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrollmentNojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eMailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfBirthjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parent_GuardianNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel8))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3))
        );

        jPanel4.setAutoscrolls(true);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Educational Qualification");

        highSchooljCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        highSchooljCheckBox.setText("High School");
        highSchooljCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highSchooljCheckBoxActionPerformed(evt);
            }
        });

        undergraduatejCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        undergraduatejCheckBox.setText("Undergraduate");

        graduatejCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        graduatejCheckBox.setText("Graduate");

        vocationalSchooljCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vocationalSchooljCheckBox.setText("Vocational School");

        othersjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        othersjCheckBox.setText("Others");

        othersjTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        othersjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersjTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(othersjCheckBox)
                            .addComponent(graduatejCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vocationalSchooljCheckBox)
                            .addComponent(othersjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(highSchooljCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(undergraduatejCheckBox)
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highSchooljCheckBox)
                    .addComponent(undergraduatejCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graduatejCheckBox)
                    .addComponent(vocationalSchooljCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(othersjCheckBox)
                    .addComponent(othersjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setAutoscrolls(true);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("How did you hear about us");

        seminarjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seminarjCheckBox.setText("Seminar");
        seminarjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seminarjCheckBoxActionPerformed(evt);
            }
        });

        magazinejCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        magazinejCheckBox.setText("Magazine");

        internetjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        internetjCheckBox.setText("Internet");

        friends_RelativesjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        friends_RelativesjCheckBox.setText("Friends/Relatives");

        othersjCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        othersjCheckBox2.setText("Others");

        othersjTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        othersjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersjTextField3ActionPerformed(evt);
            }
        });

        newspaperjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newspaperjCheckBox.setText("Newspaper");
        newspaperjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspaperjCheckBoxActionPerformed(evt);
            }
        });

        billboardjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billboardjCheckBox.setText("Billboard");
        billboardjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billboardjCheckBoxActionPerformed(evt);
            }
        });

        cinemajCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cinemajCheckBox.setText("Cinema");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seminarjCheckBox)
                    .addComponent(magazinejCheckBox)
                    .addComponent(internetjCheckBox)
                    .addComponent(friends_RelativesjCheckBox)
                    .addComponent(othersjCheckBox2))
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(othersjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billboardjCheckBox)
                    .addComponent(cinemajCheckBox)
                    .addComponent(newspaperjCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seminarjCheckBox)
                    .addComponent(newspaperjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(magazinejCheckBox)
                    .addComponent(billboardjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internetjCheckBox)
                    .addComponent(cinemajCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(friends_RelativesjCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(othersjCheckBox2)
                    .addComponent(othersjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        jPanel7.setAutoscrolls(true);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("You would like a Career in the field of:");

        marketingjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marketingjCheckBox.setText("Marketing");
        marketingjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketingjCheckBoxActionPerformed(evt);
            }
        });

        websiteDesigningjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        websiteDesigningjCheckBox.setText("Website Designing");
        websiteDesigningjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteDesigningjCheckBoxActionPerformed(evt);
            }
        });

        systemEngineerjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        systemEngineerjCheckBox.setText("System Engineer");

        softwareEngineeringjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        softwareEngineeringjCheckBox.setText("Software Engineering");
        softwareEngineeringjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softwareEngineeringjCheckBoxActionPerformed(evt);
            }
        });

        hadrware_NetworkingjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hadrware_NetworkingjCheckBox.setText("Hadrware/Networking");
        hadrware_NetworkingjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hadrware_NetworkingjCheckBoxActionPerformed(evt);
            }
        });

        educationjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        educationjCheckBox.setText("Education");

        undecidedjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        undecidedjCheckBox.setText("Undecided");
        undecidedjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undecidedjCheckBoxActionPerformed(evt);
            }
        });

        otherjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        otherjCheckBox.setText("Others(Please specify)");

        othersjTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        othersjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersjTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(softwareEngineeringjCheckBox)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marketingjCheckBox)
                            .addComponent(hadrware_NetworkingjCheckBox)
                            .addComponent(undecidedjCheckBox))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(otherjCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(educationjCheckBox)
                    .addComponent(systemEngineerjCheckBox)
                    .addComponent(websiteDesigningjCheckBox)
                    .addComponent(othersjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marketingjCheckBox)
                    .addComponent(websiteDesigningjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemEngineerjCheckBox)
                    .addComponent(softwareEngineeringjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(educationjCheckBox)
                    .addComponent(hadrware_NetworkingjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undecidedjCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherjCheckBox)
                    .addComponent(othersjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel9.setAutoscrolls(true);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("  Future Plan");

        startYourOwnBusinessjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startYourOwnBusinessjCheckBox.setText("Start your own business");
        startYourOwnBusinessjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startYourOwnBusinessjCheckBoxActionPerformed(evt);
            }
        });

        workAsAnITProfessionaljCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        workAsAnITProfessionaljCheckBox.setText("Work as an IT professional");

        goAbroadjCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goAbroadjCheckBox.setText("Go Abroad");
        goAbroadjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goAbroadjCheckBoxActionPerformed(evt);
            }
        });

        othersjCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        othersjCheckBox4.setText("Others");
        othersjCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersjCheckBox4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Do you require placement assistance");

        buttonGroup1.add(nojRadioButton);
        nojRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nojRadioButton.setText("No");

        buttonGroup1.add(yesjRadioButton);
        yesjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yesjRadioButton.setText("Yes");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(yesjRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nojRadioButton))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(workAsAnITProfessionaljCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(startYourOwnBusinessjCheckBox))
                            .addGap(8, 8, 8)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(goAbroadjCheckBox)
                                .addComponent(othersjCheckBox4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startYourOwnBusinessjCheckBox)
                    .addComponent(goAbroadjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workAsAnITProfessionaljCheckBox)
                    .addComponent(othersjCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nojRadioButton)
                    .addComponent(yesjRadioButton)))
        );

        jPanel8.setAutoscrolls(true);

        updatejButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        deletejButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        resetjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetjButton.setText("Reset");
        resetjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButtonActionPerformed(evt);
            }
        });

        prescriptionjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prescriptionjButton.setText("Enroll");
        prescriptionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionjButtonActionPerformed(evt);
            }
        });

        loginjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginjButton.setText("Logout");
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });

        exitjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitjButton.setText("Exit");
        exitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updatejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addComponent(loginjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prescriptionjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatejButton)
                    .addComponent(deletejButton)
                    .addComponent(resetjButton)
                    .addComponent(loginjButton)
                    .addComponent(prescriptionjButton)
                    .addComponent(exitjButton)))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );

        jTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date of Enrollment", "Enrollment No", "First Name", "Last Name", "Address", "Contact No", "E-Mail", "Date of Birth", "Parents/Guardian's Name", "Contact No", "Educational Qualification", "Career", "How did you hear about us?", "Future Plan", "placement assistance"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateOfEnrollmentjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfEnrollmentjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfEnrollmentjTextFieldActionPerformed

    private void enrollmentNojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentNojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentNojTextFieldActionPerformed

    private void highSchooljCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highSchooljCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highSchooljCheckBoxActionPerformed

    private void othersjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_othersjTextField1ActionPerformed

    private void seminarjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seminarjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seminarjCheckBoxActionPerformed

    private void othersjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_othersjTextField3ActionPerformed

    private void newspaperjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspaperjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newspaperjCheckBoxActionPerformed

    private void marketingjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketingjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marketingjCheckBoxActionPerformed

    private void websiteDesigningjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteDesigningjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_websiteDesigningjCheckBoxActionPerformed

    private void othersjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_othersjTextField2ActionPerformed

    private void hadrware_NetworkingjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hadrware_NetworkingjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hadrware_NetworkingjCheckBoxActionPerformed

    private void undecidedjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undecidedjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undecidedjCheckBoxActionPerformed

    private void startYourOwnBusinessjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startYourOwnBusinessjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startYourOwnBusinessjCheckBoxActionPerformed

    private void goAbroadjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goAbroadjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goAbroadjCheckBoxActionPerformed

    private void othersjCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersjCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_othersjCheckBox4ActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
    String[] textField = {dateOfEnrollmentjTextField.getText(), enrollmentNojTextField.getText(),firstNamejTextField.getText(),lastNamejTextField.getText(),
            addressjTextField.getText(),contactNojTextField.getText(),eMailjTextField.getText(),dateOfBirthjTextField.getText(),parent_GuardianNamejTextField1.getText(),
           contactNojTextField1.getText()};
     
        
        JCheckBox[] checkBox ={highSchooljCheckBox,graduatejCheckBox,othersjCheckBox,undergraduatejCheckBox
        ,vocationalSchooljCheckBox};
                   
              JCheckBox[] checkBox2 ={marketingjCheckBox,softwareEngineeringjCheckBox,
            hadrware_NetworkingjCheckBox, undecidedjCheckBox, otherjCheckBox, websiteDesigningjCheckBox,systemEngineerjCheckBox
,educationjCheckBox};
              
        JCheckBox[] checkBox3 ={      seminarjCheckBox, magazinejCheckBox,internetjCheckBox,
friends_RelativesjCheckBox,othersjCheckBox2,newspaperjCheckBox,  billboardjCheckBox,
        cinemajCheckBox};
        
      JCheckBox[] checkBox4 ={ startYourOwnBusinessjCheckBox, goAbroadjCheckBox, workAsAnITProfessionaljCheckBox,
         othersjCheckBox4};
      
        JRadioButton[] radioButton ={yesjRadioButton,nojRadioButton};
         int count = 0;
         
         for(String str : textField)
           {
               if(str.equals(""))
               {
                   count++;
               }
           }
           
            String education = "";
           
          for(JCheckBox jcb1 : checkBox)
          {
              if(jcb1.isSelected())
              {
                  education += jcb1.getText() + " ";
              }
          }
          
           String career = "";
           
          for(JCheckBox jcb2 : checkBox2)
          {
              if(jcb2.isSelected())
              {
                  career += jcb2.getText() + " ";
              }
          }

           String aboutUs = "";
           
          for(JCheckBox jcb3 : checkBox3)
          {
              if(jcb3.isSelected())
              {
                  aboutUs += jcb3.getText() + " ";
              }
          }
          
          String future_Plan = "";
           
          for(JCheckBox jcb4 : checkBox4)
          {
              if(jcb4.isSelected())
              {
              future_Plan += jcb4.getText() + " ";
              }
          }
          
          
           String placement_Assistance = "";
           
          for(JRadioButton jcb5 : radioButton)
          {
              if(jcb5.isSelected())
              {
placement_Assistance = jcb5.getText();
              }
          }
          
          if(count > 0)
           {
               String string = "Sorry You Have to fill all your the details in this form Before You Can Update";
               JOptionPane.showMessageDialog(null, string);
           }
          else{
        DefaultTableModel model = (DefaultTableModel)   jTable.getModel();
        model.addRow(new Object[]{
            dateOfEnrollmentjTextField.getText(), enrollmentNojTextField.getText(),firstNamejTextField.getText(),lastNamejTextField.getText(),
            addressjTextField.getText(),contactNojTextField.getText(),eMailjTextField.getText(),dateOfBirthjTextField.getText(),parent_GuardianNamejTextField1.getText(),
           contactNojTextField1.getText(),education+othersjTextField1.getText(),career+othersjTextField2.getText(),aboutUs+othersjTextField3.getText(),future_Plan,placement_Assistance
        


});
         String[] education1 = new String[] {education+" "+othersjTextField1.getText()};
                         String[] career1 = new String[] {career+" "+othersjTextField1.getText()};
                         String[] aboutUs1 = new String[] {aboutUs+" "+othersjTextField1.getText()};

        values = new String[] {
            dateOfEnrollmentjTextField.getText(), enrollmentNojTextField.getText(),firstNamejTextField.getText(),lastNamejTextField.getText(),
            addressjTextField.getText(),contactNojTextField.getText(),eMailjTextField.getText(),dateOfBirthjTextField.getText(),parent_GuardianNamejTextField1.getText(),
           contactNojTextField1.getText(),
        education1.toString(),career1.toString(),aboutUs1.toString(),future_Plan,placement_Assistance};
               
               insertData(values);  
               
          }
          
                        


    // TODO add your handling code here:
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel)   jTable.getModel();
        if(jTable.getSelectedRow()==-1){

            if(jTable.getSelectedRowCount()==0)
            {
                JOptionPane.showMessageDialog(null,"No Data to Delete", "Aptech Enquiry System",JOptionPane.OK_OPTION );
            }
            else{
                JOptionPane.showMessageDialog(null,"Select a Row to Delete", "Aptech Enquiry System",JOptionPane.OK_OPTION );

            }}
            else{
                model.removeRow(jTable.getSelectedRow());
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void resetjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButtonActionPerformed

        dateOfEnrollmentjTextField.setText("");
        enrollmentNojTextField.setText("");
        firstNamejTextField.setText("");
        lastNamejTextField.setText("");
        addressjTextField.setText("");
        contactNojTextField.setText("");
        eMailjTextField.setText("");
        dateOfBirthjTextField.setText("");
        parent_GuardianNamejTextField1.setText("");
        contactNojTextField1.setText("");
        othersjTextField1.setText("");
        othersjTextField2.setText("");
        othersjTextField3.setText("");
        highSchooljCheckBox.setSelected(false);
        graduatejCheckBox.setSelected(false);
        othersjCheckBox.setSelected(false);
        undergraduatejCheckBox.setSelected(false);
        vocationalSchooljCheckBox.setSelected(false);
        marketingjCheckBox.setSelected(false);
        softwareEngineeringjCheckBox.setSelected(false);
        hadrware_NetworkingjCheckBox.setSelected(false);
        undecidedjCheckBox.setSelected(false);
        otherjCheckBox.setSelected(false);
        websiteDesigningjCheckBox.setSelected(false);
        systemEngineerjCheckBox.setSelected(false);
        educationjCheckBox.setSelected(false);
        seminarjCheckBox.setSelected(false);
        magazinejCheckBox.setSelected(false);
        internetjCheckBox.setSelected(false);
        friends_RelativesjCheckBox.setSelected(false);
        othersjCheckBox2.setSelected(false);
        newspaperjCheckBox.setSelected(false);
        billboardjCheckBox.setSelected(false);
        cinemajCheckBox.setSelected(false);
        friends_RelativesjCheckBox.setSelected(false);
        startYourOwnBusinessjCheckBox.setSelected(false);
        goAbroadjCheckBox.setSelected(false);
        workAsAnITProfessionaljCheckBox.setSelected(false);
        othersjCheckBox4.setSelected(false);
        yesjRadioButton.setSelected(false);
        nojRadioButton.setSelected(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_resetjButtonActionPerformed

    private void prescriptionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionjButtonActionPerformed
        

        this.setVisible(false);
      EnrollmentSystem enroll = new EnrollmentSystem();
        enroll.setVisible(true);
        
        namejTextField.setText(firstNamejTextField.getText()+" "+lastNamejTextField.getText());
       datejTextField.setText(dateOfEnrollmentjTextField.getText());
    }//GEN-LAST:event_prescriptionjButtonActionPerformed

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed

        this.setVisible(false);
        EnquirySystem logout = new EnquirySystem();
        logout.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_loginjButtonActionPerformed

    private void exitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjButtonActionPerformed

        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit","This Hospital Management System",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
    System.exit(0);

    }//GEN-LAST:event_exitjButtonActionPerformed

    private void softwareEngineeringjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softwareEngineeringjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_softwareEngineeringjCheckBoxActionPerformed

    private void billboardjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billboardjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billboardjCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnquirySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnquirySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnquirySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnquirySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnquirySystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjTextField;
    private javax.swing.JCheckBox billboardjCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cinemajCheckBox;
    private javax.swing.JTextField contactNojTextField;
    private javax.swing.JTextField contactNojTextField1;
    private javax.swing.JTextField dateOfBirthjTextField;
    private javax.swing.JTextField dateOfEnrollmentjTextField;
    private javax.swing.JButton deletejButton;
    private javax.swing.JTextField eMailjTextField;
    private javax.swing.JCheckBox educationjCheckBox;
    private javax.swing.JTextField enrollmentNojTextField;
    private javax.swing.JButton exitjButton;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JCheckBox friends_RelativesjCheckBox;
    private javax.swing.JCheckBox goAbroadjCheckBox;
    private javax.swing.JCheckBox graduatejCheckBox;
    private javax.swing.JCheckBox hadrware_NetworkingjCheckBox;
    private javax.swing.JCheckBox highSchooljCheckBox;
    private javax.swing.JCheckBox internetjCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField lastNamejTextField;
    private javax.swing.JButton loginjButton;
    private javax.swing.JCheckBox magazinejCheckBox;
    private javax.swing.JCheckBox marketingjCheckBox;
    private javax.swing.JCheckBox newspaperjCheckBox;
    private javax.swing.JRadioButton nojRadioButton;
    private javax.swing.JCheckBox otherjCheckBox;
    private javax.swing.JCheckBox othersjCheckBox;
    private javax.swing.JCheckBox othersjCheckBox2;
    private javax.swing.JCheckBox othersjCheckBox4;
    private javax.swing.JTextField othersjTextField1;
    private javax.swing.JTextField othersjTextField2;
    private javax.swing.JTextField othersjTextField3;
    private javax.swing.JTextField parent_GuardianNamejTextField1;
    private javax.swing.JButton prescriptionjButton;
    private javax.swing.JButton resetjButton;
    private javax.swing.JCheckBox seminarjCheckBox;
    private javax.swing.JCheckBox softwareEngineeringjCheckBox;
    private javax.swing.JCheckBox startYourOwnBusinessjCheckBox;
    private javax.swing.JCheckBox systemEngineerjCheckBox;
    private javax.swing.JCheckBox undecidedjCheckBox;
    private javax.swing.JCheckBox undergraduatejCheckBox;
    private javax.swing.JButton updatejButton;
    private javax.swing.JCheckBox vocationalSchooljCheckBox;
    private javax.swing.JCheckBox websiteDesigningjCheckBox;
    private javax.swing.JCheckBox workAsAnITProfessionaljCheckBox;
    private javax.swing.JRadioButton yesjRadioButton;
    // End of variables declaration//GEN-END:variables
}
