/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EnrollmentApp;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import EnrollmentApp.Print;
import static EnrollmentApp.PrintReceipt.DrawnOnTextField;
import static EnrollmentApp.PrintReceipt.cashAmountTextField3;
import static EnrollmentApp.PrintReceipt.cautionDepositTextField;
import static EnrollmentApp.PrintReceipt.chequeAmountTextField3;
import static EnrollmentApp.PrintReceipt.courseFeeTextField1;
import static EnrollmentApp.PrintReceipt.dateTextField;
import static EnrollmentApp.PrintReceipt.dateTextField2;
import static EnrollmentApp.PrintReceipt.equalTextField1;
import static EnrollmentApp.PrintReceipt.equalTextField2;
import static EnrollmentApp.PrintReceipt.equalTextField3;
import static EnrollmentApp.PrintReceipt.equalTextField4;
import static EnrollmentApp.PrintReceipt.equalTextField5;
import static EnrollmentApp.PrintReceipt.equalTextField6;
import static EnrollmentApp.PrintReceipt.equalTextField7;
import static EnrollmentApp.PrintReceipt.examFeeTextField1;
import static EnrollmentApp.PrintReceipt.invoiceNoTextField;
import static EnrollmentApp.PrintReceipt.lateFeeTextField1;
import static EnrollmentApp.PrintReceipt.methodOfPaymentTextField;
import static EnrollmentApp.PrintReceipt.nameTextField;
import static EnrollmentApp.PrintReceipt.othersTextField1;
import static EnrollmentApp.PrintReceipt.prospectusTextField1;
import static EnrollmentApp.PrintReceipt.receiptNoTextField;
import static EnrollmentApp.PrintReceipt.receivedTextField;
import static EnrollmentApp.PrintReceipt.rollNoTextField;
import static EnrollmentApp.PrintReceipt.totalTextField2;
/**
 *
 * @author Godswill
 */
public class EnrollmentSystem extends javax.swing.JFrame {

    double answer, number;
    private JFrame frame;
private static final String url ="jdbc:mysql://localhost:3306";
    private static final String userName = "root";
    private static final String password2="plexus7989";
    
    static Connection connect = null;
    
    public static void EnquirySystem(){
    
     try{
    
    connect = DriverManager.getConnection(url, userName, password2);
    
            System.out.println("Connection Successful");
            
}
       catch(SQLException e){
    System.err.print(e);
}
    
}
    
    private static void insertData(String[] arrayOfDetails){
        EnquirySystem();
        try{
       PreparedStatement  prepared = connect.prepareStatement("INSERT INTO aptechikorodu.enrollment_system_table(receiptNo,date,invoiceNo,rollNo,received,name,courseFee,examFee,lateFee,prospectus,cautionDeposit,others,total,methodOfPayment,date2,DrawnOn,chequeAmount,cashAmount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
      
       
       int count = arrayOfDetails.length;
       
       int noo = 1;
       for(int i=0; i < (count); i++)
       {
           
           prepared.setObject(noo, arrayOfDetails[i]);
           noo++;
       }
        
        prepared.executeUpdate();
        
        String string = "The Details Has Been Inserted Successfully into The Database!";
        JOptionPane.showMessageDialog(null, string);        
        }
        catch(SQLException e){
            System.err.println(e);
        }
        
    }
    private double answer1;
    private double answer2;
    private double answer3;
    private double answer4;
    private double answer5;
    private double total;
    /**
     * Creates new form EnrollmentSystem
     */
    public EnrollmentSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        receiptNojTextField = new javax.swing.JTextField();
        datejTextField = new javax.swing.JTextField();
        invoiceNojTextField = new javax.swing.JTextField();
        rollNojTextField = new javax.swing.JTextField();
        receivedjTextField = new javax.swing.JTextField();
        namejTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptjTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        courseFeejTextField1 = new javax.swing.JTextField();
        examFeejTextField1 = new javax.swing.JTextField();
        lateFeejTextField1 = new javax.swing.JTextField();
        prospectusjTextField1 = new javax.swing.JTextField();
        cautionDepositjTextField = new javax.swing.JTextField();
        othersjTextField1 = new javax.swing.JTextField();
        equaljTextField1 = new javax.swing.JTextField();
        equaljTextField5 = new javax.swing.JTextField();
        equaljTextField6 = new javax.swing.JTextField();
        equaljTextField2 = new javax.swing.JTextField();
        equaljTextField4 = new javax.swing.JTextField();
        equaljTextField3 = new javax.swing.JTextField();
        totaljTextField2 = new javax.swing.JTextField();
        equaljTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        methodOfPaymentjTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        datejTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        DrawnOnjTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        chequeAmountjTextField3 = new javax.swing.JTextField();
        cashAmountjTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        updatejButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        resetjButton = new javax.swing.JButton();
        logoutjButton = new javax.swing.JButton();
        printReceiptJButton = new javax.swing.JButton();
        exitjButton = new javax.swing.JButton();
        displayReceiptjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EnrollmentSystem");
        setMinimumSize(new java.awt.Dimension(700, 400));
        setName("EnrollmentSystem"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Godswill\\Downloads\\aptech logo.png")); // NOI18N
        jButton1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("ENROLLMENT SYSTEM");

        jPanel1.setAutoscrolls(true);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("RECEIPT NO.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("DATE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("INVOICE NO.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ROLL NO.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("RECEIVED The Sum of");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Mr/Mrs/Ms");

        receiptNojTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        receiptNojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptNojTextFieldActionPerformed(evt);
            }
        });

        datejTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datejTextFieldActionPerformed(evt);
            }
        });

        invoiceNojTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        rollNojTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        receivedjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        namejTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Naira");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("from");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("towards");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rollNojTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                            .addComponent(datejTextField)
                            .addComponent(invoiceNojTextField)
                            .addComponent(receiptNojTextField))
                        .addGap(227, 227, 227))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namejTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(receivedjTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptNojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollNojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receivedjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)))
        );

        jPanel2.setAutoscrolls(true);

        receiptjTextArea.setEditable(false);
        receiptjTextArea.setColumns(20);
        receiptjTextArea.setRows(5);
        jScrollPane1.setViewportView(receiptjTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setAutoscrolls(true);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Course Fee");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Exam Fee");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Late Fee");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Prospectus");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Caution Deposit");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Others");

        courseFeejTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        courseFeejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseFeejTextField1ActionPerformed(evt);
            }
        });

        examFeejTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        examFeejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examFeejTextField1ActionPerformed(evt);
            }
        });

        lateFeejTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        prospectusjTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cautionDepositjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        othersjTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        equaljTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        equaljTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equaljTextField1ActionPerformed(evt);
            }
        });

        equaljTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        equaljTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        equaljTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        equaljTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equaljTextField2ActionPerformed(evt);
            }
        });

        equaljTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        equaljTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        totaljTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        equaljTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Total");
        jButton2.setToolTipText("Click Me To Calculate The Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totaljTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(othersjTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(cautionDepositjTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(prospectusjTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lateFeejTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(examFeejTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(courseFeejTextField1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(equaljTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(equaljTextField6)
                    .addComponent(equaljTextField5)
                    .addComponent(equaljTextField4)
                    .addComponent(equaljTextField3)
                    .addComponent(equaljTextField2)
                    .addComponent(equaljTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equaljTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseFeejTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(equaljTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(equaljTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(equaljTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(equaljTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(equaljTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equaljTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaljTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(examFeejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lateFeejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prospectusjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cautionDepositjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(othersjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jPanel4.setAutoscrolls(true);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("By Cash/Cheque No.");

        methodOfPaymentjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        methodOfPaymentjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodOfPaymentjTextFieldActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("Dated");

        datejTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datejTextField2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setText("Drawn on");

        DrawnOnjTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setText("Cheque Amount");

        chequeAmountjTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cashAmountjTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setText("Cash Amount");
        jButton3.setToolTipText("Click Me To Calculate The Cash Amount");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jButton3))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashAmountjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DrawnOnjTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(datejTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(methodOfPaymentjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chequeAmountjTextField3)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(methodOfPaymentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DrawnOnjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chequeAmountjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cashAmountjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("RECEIPT");

        jPanel8.setAutoscrolls(true);

        updatejButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        deletejButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        resetjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetjButton.setText("Reset");
        resetjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButtonActionPerformed(evt);
            }
        });

        logoutjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logoutjButton.setText("Back");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        printReceiptJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        printReceiptJButton.setText("Print Receipt");
        printReceiptJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReceiptJButtonActionPerformed(evt);
            }
        });

        exitjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitjButton.setText("Exit");
        exitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjButtonActionPerformed(evt);
            }
        });

        displayReceiptjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        displayReceiptjButton.setText("Desplay Receipt");
        displayReceiptjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayReceiptjButtonActionPerformed(evt);
            }
        });

        jTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt No", "Date", "Invoice No", "Roll No", "Received the sum of", "Name", "Course Fee", "Exam Fee", "Late Fee", "Prospectus", "Caution Deposit", "Others", "Total", "Payment Mode", "Dated", "Drawn on", "Cheque Amount", "Cash Amount"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(updatejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayReceiptjButton)
                        .addGap(18, 18, 18)
                        .addComponent(printReceiptJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(logoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(exitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetjButton)
                    .addComponent(deletejButton)
                    .addComponent(updatejButton)
                    .addComponent(logoutjButton)
                    .addComponent(exitjButton)
                    .addComponent(printReceiptJButton)
                    .addComponent(displayReceiptjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(486, 486, 486)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(477, 477, 477)
                        .addComponent(jLabel2)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receiptNojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptNojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptNojTextFieldActionPerformed

    private void datejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datejTextFieldActionPerformed

    private void examFeejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examFeejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examFeejTextField1ActionPerformed

    private void courseFeejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseFeejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseFeejTextField1ActionPerformed

    private void equaljTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equaljTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equaljTextField1ActionPerformed

    private void equaljTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equaljTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equaljTextField2ActionPerformed

    private void methodOfPaymentjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodOfPaymentjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodOfPaymentjTextFieldActionPerformed

    private void datejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datejTextField2ActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed

        DefaultTableModel model = (DefaultTableModel)   jTable.getModel();
        model.addRow(new Object[]{
            receiptNojTextField.getText(), datejTextField.getText(),invoiceNojTextField.getText(),rollNojTextField.getText(),
            receivedjTextField.getText(),namejTextField.getText(),courseFeejTextField1.getText(),examFeejTextField1.getText(),lateFeejTextField1.getText(),
            prospectusjTextField1.getText(),cautionDepositjTextField.getText(),othersjTextField1.getText(),totaljTextField2.getText(),
        methodOfPaymentjTextField.getText(),datejTextField2.getText(),DrawnOnjTextField.getText(),chequeAmountjTextField3.getText(),cashAmountjTextField3.getText()});

        
        //for database
         String[] values = new String[] {
         
         receiptNojTextField.getText(), datejTextField.getText(),invoiceNojTextField.getText(),rollNojTextField.getText(),
            receivedjTextField.getText(),namejTextField.getText(),courseFeejTextField1.getText(),examFeejTextField1.getText(),lateFeejTextField1.getText(),
            prospectusjTextField1.getText(),cautionDepositjTextField.getText(),othersjTextField1.getText(),totaljTextField2.getText(),
        methodOfPaymentjTextField.getText(),datejTextField2.getText(),DrawnOnjTextField.getText(),chequeAmountjTextField3.getText(),cashAmountjTextField3.getText()
};
                                 insertData(values);  

    // TODO add your handling code here:
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel)   jTable.getModel();
        if(jTable.getSelectedRow()==-1){

            if(jTable.getSelectedRowCount()==0)
            {
                JOptionPane.showMessageDialog(null,"No Data to Delete", "Aptech Enrollment System",JOptionPane.OK_OPTION );
            }
            else{
                JOptionPane.showMessageDialog(null,"Select a Row to Delete", "Aptech Enrollment System",JOptionPane.OK_OPTION );

            }}
            else{
                model.removeRow(jTable.getSelectedRow());
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void resetjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButtonActionPerformed

        receiptNojTextField.setText("");
        datejTextField.setText("");
        invoiceNojTextField.setText("");
        rollNojTextField.setText("");
        receivedjTextField.setText("");
        namejTextField.setText("");
        courseFeejTextField1.setText("");
        examFeejTextField1.setText("");
        lateFeejTextField1.setText("");
        prospectusjTextField1.setText("");
        cautionDepositjTextField.setText("");
        othersjTextField1.setText("");
        totaljTextField2.setText("");
        equaljTextField1.setText("");
        equaljTextField2.setText("");
        equaljTextField3.setText("");
        equaljTextField4.setText("");
        equaljTextField5.setText("");
        equaljTextField6.setText("");
        equaljTextField7.setText("");
        methodOfPaymentjTextField.setText("");
datejTextField2.setText("");
DrawnOnjTextField.setText("");
chequeAmountjTextField3.setText("");
cashAmountjTextField3.setText("");
receiptjTextArea.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_resetjButtonActionPerformed

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed

        this.setVisible(false);
       EnquirySystem enquiry = new    EnquirySystem();
        enquiry.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void printReceiptJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReceiptJButtonActionPerformed
    /*   this.setVisible(false);
       Print print = new   Print();
        print.setVisible(true);
        
       
        
  receiptNoTextField.setText(EnrollmentApp.EnrollmentSystem.receiptNojTextField.getText());
    dateTextField.setText(EnrollmentApp.EnrollmentSystem.datejTextField.getText());
     invoiceNoTextField.setText(EnrollmentApp.EnrollmentSystem.invoiceNojTextField.getText());
      rollNoTextField.setText(EnrollmentApp.EnrollmentSystem.rollNojTextField.getText());
       receivedTextField.setText(EnrollmentApp.EnrollmentSystem.receivedjTextField.getText());
        nameTextField.setText(EnrollmentApp.EnrollmentSystem.namejTextField.getText());
         courseFeeTextField1.setText(EnrollmentApp.EnrollmentSystem.courseFeejTextField1.getText());
          equalTextField1.setText(EnrollmentApp.EnrollmentSystem.equaljTextField1.getText());
           examFeeTextField1.setText(EnrollmentApp.EnrollmentSystem.examFeejTextField1.getText());
            equalTextField2.setText(EnrollmentApp.EnrollmentSystem.equaljTextField2.getText());
             lateFeeTextField1.setText(EnrollmentApp.EnrollmentSystem.lateFeejTextField1.getText());
                equalTextField3.setText(EnrollmentApp.EnrollmentSystem.equaljTextField3.getText());
               prospectusTextField1.setText(EnrollmentApp.EnrollmentSystem.prospectusjTextField1.getText());
               equalTextField4.setText(EnrollmentApp.EnrollmentSystem.equaljTextField4.getText());
             cautionDepositTextField.setText(EnrollmentApp.EnrollmentSystem.cautionDepositjTextField.getText());
             equalTextField5.setText(EnrollmentApp.EnrollmentSystem.equaljTextField5.getText());
            othersTextField1.setText(EnrollmentApp.EnrollmentSystem.othersjTextField1.getText());  
              equalTextField6.setText(EnrollmentApp.EnrollmentSystem.equaljTextField6.getText());
             totalTextField2.setText(EnrollmentApp.EnrollmentSystem.totaljTextField2.getText());
             equalTextField7.setText(EnrollmentApp.EnrollmentSystem.equaljTextField7.getText());
            othersTextField1.setText(EnrollmentApp.EnrollmentSystem.othersjTextField1.getText());
            methodOfPaymentTextField.setText(EnrollmentApp.EnrollmentSystem.methodOfPaymentjTextField.getText());
             dateTextField2.setText(EnrollmentApp.EnrollmentSystem.datejTextField2.getText());
             DrawnOnTextField.setText(EnrollmentApp.EnrollmentSystem.DrawnOnjTextField.getText());
            chequeAmountTextField3.setText(EnrollmentApp.EnrollmentSystem.chequeAmountjTextField3.getText());
            cashAmountTextField3.setText(EnrollmentApp.EnrollmentSystem.cashAmountjTextField3.getText());
        
        */
    
   // Print print = new   Print();
    
    try{
            receiptjTextArea.print();
        }
        catch(PrinterException print){
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(Level.SEVERE,null,print);
        }

    }//GEN-LAST:event_printReceiptJButtonActionPerformed

    private void exitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjButtonActionPerformed

        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit","Aptech Enrollment System",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
    System.exit(0);
    }//GEN-LAST:event_exitjButtonActionPerformed

    private void displayReceiptjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayReceiptjButtonActionPerformed
        String qty1 =(receiptNojTextField.getText());
        String qty2 =(datejTextField.getText());
        String qty3 =(invoiceNojTextField.getText());
        String qty4 =(rollNojTextField.getText());
        String qty5 =(receivedjTextField.getText());
        String qty6 =(namejTextField.getText());
        String qty7 =(courseFeejTextField1.getText());
        String qty8 =(equaljTextField1.getText());
        String qty9 =(examFeejTextField1.getText());
        String qty10 =(equaljTextField2.getText());
        String qty11 =(lateFeejTextField1.getText());
        String qty12 =(equaljTextField3.getText());
        String qty13 =(prospectusjTextField1.getText());
        String qty14 =(equaljTextField4.getText());
        String qty15 =(cautionDepositjTextField.getText());
        String qty16 =(equaljTextField5.getText());
        String qty17 =(othersjTextField1.getText());
        String qty18 =(equaljTextField6.getText());
        String qty19 =(totaljTextField2.getText());
        String qty20 =(equaljTextField7.getText());
        String qty21 =(methodOfPaymentjTextField.getText());
        String qty22 =(datejTextField2.getText());
        String qty23 =(DrawnOnjTextField.getText());
        String qty24 =(chequeAmountjTextField3.getText());
        String qty25 =(cashAmountjTextField3.getText());      
        
        receiptjTextArea.createImage(690,700);
        JTextPane jTextPane = new JTextPane();
        JScrollPane pane = new JScrollPane(jTextPane);
        add(pane);
        
        receiptjTextArea.append("\t\tRECEIPT\n"
            + " RECEIPT NO.:\t"+qty1
            + "\n\n DATE:\t\t"+qty2
            + "\n\n INVOICE NO.:\t"+qty3
            + "\n\n ROLL NO.:\t\t"+qty4
            + "\n\n RECEIVED The Sum of:\t"+qty5
            + "\n\n Mr/Mrs/Ms:\t\t"+qty6
            + "\n\n\n Course Fee:\t\t"+qty7
            +qty8
                            + "\t By Cash/Cheque No.:\t"+qty21
            + "\n\n Exam Fee:\t\t"+qty9
            +qty1                                                                               
                            + "\t Dated:\t\t"+qty22

            + "\n\n Late Fee:\t\t"+qty11
            +qty12
                            + "\t Drawn on:\t\t"+qty23

            + "\n\n Prospectus:\t\t"+qty13
            +qty14
                            + "\t Cheque Amount:\t"+qty24

            + "\n\n Caution Deposit:\t"+qty15
            +qty16
                            + "\t Cash Amount:\t"+qty25

            + "\n\n Others:\t\t"+qty17
            +qty18
                            
        + "\n\n Total:\t\t"+qty19
            +qty20
                + "\t For:\tKingsBridge(BSO Ltd)"
                                             + "\n\t\t\t -------------------------------------------------"
                            + "\n\t\t\t\tAptech Worldwide"
                  
          + "\n\nCHEQUES SUBJECT TO REALISATION"
    
        + "\nTHIS RECEIPT MUST BE PRODUCED WHEN DEMANDED" 
        + "\nFEES ONCE PAID ARE NOT REFUNDABLE"
        + "\nSUBJECT TO TERMS AND CONDITIONS PRINTED OVERLEAF THE INVOICE"
         + "\n\n\n\t\t\t\tAuthorised Signatory"
       + "\n--------------------------------------------------------------------------------------------------------------"
 + "\nAptech Computer Education, 1st Floor, 241, Lagos Road, Opposite Govt. College,"
                        + "\n\t\t Idiroko Bus Stop, Ikorodu, Lagos."
         + "\n\t\tTel:A 09031518812, 08086161583"
   + "\ne-mail: info@aptechikoroducenter.com  www.aptechikoroducenter.com  "
                        + "\n\t\taptechikoroducenter"


        );

        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_displayReceiptjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
chequeAmountjTextField3.setText(totaljTextField2.getText());
cashAmountjTextField3.setText(totaljTextField2.getText());
datejTextField2.setText(datejTextField.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    answer = Double.parseDouble(courseFeejTextField1.getText());
    answer1 =Double.parseDouble(examFeejTextField1.getText());
    answer2 =Double.parseDouble(lateFeejTextField1.getText());
    answer3 =Double.parseDouble(prospectusjTextField1.getText());
    answer4 =Double.parseDouble(cautionDepositjTextField.getText());
    answer5 =Double.parseDouble(othersjTextField1.getText());
    total = answer+answer1+answer2+answer3+answer4+answer5;
                totaljTextField2.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrollmentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollmentSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField DrawnOnjTextField;
    public static javax.swing.JTextField cashAmountjTextField3;
    public static javax.swing.JTextField cautionDepositjTextField;
    public static javax.swing.JTextField chequeAmountjTextField3;
    public static javax.swing.JTextField courseFeejTextField1;
    public static javax.swing.JTextField datejTextField;
    public static javax.swing.JTextField datejTextField2;
    private javax.swing.JButton deletejButton;
    private javax.swing.JButton displayReceiptjButton;
    public static javax.swing.JTextField equaljTextField1;
    public static javax.swing.JTextField equaljTextField2;
    public static javax.swing.JTextField equaljTextField3;
    public static javax.swing.JTextField equaljTextField4;
    public static javax.swing.JTextField equaljTextField5;
    public static javax.swing.JTextField equaljTextField6;
    public static javax.swing.JTextField equaljTextField7;
    public static javax.swing.JTextField examFeejTextField1;
    private javax.swing.JButton exitjButton;
    public static javax.swing.JTextField invoiceNojTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    public static javax.swing.JTextField lateFeejTextField1;
    private javax.swing.JButton logoutjButton;
    public static javax.swing.JTextField methodOfPaymentjTextField;
    public static javax.swing.JTextField namejTextField;
    public static javax.swing.JTextField othersjTextField1;
    private javax.swing.JButton printReceiptJButton;
    public static javax.swing.JTextField prospectusjTextField1;
    public static javax.swing.JTextField receiptNojTextField;
    private javax.swing.JTextArea receiptjTextArea;
    public static javax.swing.JTextField receivedjTextField;
    private javax.swing.JButton resetjButton;
    public static javax.swing.JTextField rollNojTextField;
    public static javax.swing.JTextField totaljTextField2;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
